# Generated by Django 5.1.2 on 2024-10-25 16:12

from django.db import migrations
from phonenumbers import parse, is_valid_number, format_number, PhoneNumberFormat


def normalize_phone(phone_number):
    if not phone_number:
        return None
    parsed_number = parse(phone_number, 'RU')
    return format_number(parsed_number, PhoneNumberFormat.INTERNATIONAL) if is_valid_number(parsed_number) else None


def transfer_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    owner_dict = {}

    for flat in Flat.objects.all():

        if flat.owner not in owner_dict:
            owner_dict[flat.owner] = Owner.objects.create(
                name=flat.owner,
                phone_number=flat.owners_phonenumber,
                normalized_phone=normalize_phone(flat.owners_phonenumber)
            )

        owner_dict[flat.owner].flats.add(flat)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0012_auto_20241025_1841'),
    ]

    operations = [
        migrations.RunPython(transfer_owners),
    ]
