# Generated by Django 5.1.2 on 2024-10-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_remove_flat_owner_alter_owner_flats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
